# Generated by Django 3.2.7 on 2021-10-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_auto_20210925_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='identity',
            field=models.CharField(default='identity', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='strength',
            field=models.CharField(default='strength', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='weakness',
            field=models.CharField(default='weakness', max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
