# Generated by Django 3.2.7 on 2021-11-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_auto_20211005_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.CharField(default='link to image', max_length=100),
        ),
    ]
